version: "2.2"
services:
  castor:
    build:
      context: .
      dockerfile: Dockerfile.castor
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - /var/log/postgresql:/var/log/posgresql
    env_file: .env
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
